// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/common/Banner.vue')['default']
    CoverItem: typeof import('./src/components/common/CoverItem.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./src/components/layout/footer/Footer.vue')['default']
    Header: typeof import('./src/components/layout/header/Header.vue')['default']
    IconSvg: typeof import('./src/components/common/IconSvg.vue')['default']
    PlayList: typeof import('./src/components/common/PlayList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
